### ISSUE TITLE
AWS FMS: SecurityServicePolicyData rendering entirely as JSON

### ISSUE THREAD

**Issue by ev3rl0ng** [cloudtools/troposphere#1834]
By [AWS CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fms-policy.html#aws-resource-fms-policy--examples), the YAML representation of the SecurityServicePolicyData has two child nodes... _Type_ and _ManagedServiceData_. They are represented in YAML as follows:

```yaml
PolicyWAFv2:
    Type: AWS::FMS::Policy
    Properties:
      ExcludeResourceTags: false
      PolicyName: Policy
      RemediationEnabled: false 
      ResourceType: AWS::ElasticLoadBalancingV2::LoadBalancer 
      SecurityServicePolicyData: 
        Type: WAFV2
        ManagedServiceData: !Sub '{"type":"WAFV2", 
                                  "preProcessRuleGroups":[{ 
                                  "ruleGroupType":"RuleGroup",
                                  "ruleGroupArn":"${RuleGroup.Arn}",
                                  "overrideAction":{"type":"NONE"}}],
                                  "postProcessRuleGroups":[],
                                  "defaultAction":{"type":"BLOCK"}}' 
```

The _ManagedServiceData_ property is the only item of the node that is supposed to be JSON based, but in the [FMS::Policy troposphere object](https://github.com/cloudtools/troposphere/blob/26d0663e7ad5ac632a5aeaee34d66ded8195a116/troposphere/fms.py#L31), the entire thing is coded/output as JSON, which results in outputs like this:

```yaml
  BaseProtectionsIntPolicy:
    Properties:
      DeleteAllPolicyResources: true
      ExcludeResourceTags: false
      IncludeMap:
        ACCOUNT:
          - '123456789012'
        ORGUNIT: []
      PolicyName: Base-Protections-Int-Policy
      RemediationEnabled: false
      ResourceType: ResourceTypeList
      ResourceTypeList:
        - AWS::ElasticLoadBalancingV2::LoadBalancer
        - AWS::ApiGateway::Stage
      SecurityServicePolicyData: >-
        {"type": "WAFV2", "ManagedServiceData": "{\"type\": \"WAFV2\", \"preProcessRuleGroups\":
        [{\"ruleGroupArn\": null, \"overrideAction\": {\"type\": \"COUNT\"}, \"managedRuleGroupIdentifier\":
        {\"version\": null, \"vendorName\": \"AWS\", \"managedRuleGroupName\": \"AWSManagedRulesCommonRuleSet\"},
        \"ruleGroupType\": \"ManagedRuleGroup\"}, {\"ruleGroupArn\": null, \"overrideAction\":
        {\"type\": \"COUNT\"}, \"managedRuleGroupIdentifier\": {\"version\": null,
        \"vendorName\": \"AWS\", \"managedRuleGroupName\": \"AWSManagedRulesAmazonIpReputationList\"},
        \"ruleGroupType\": \"ManagedRuleGroup\"}, {\"ruleGroupArn\": \"${BaseIntRuleGroup.Arn}\",
        \"overrideAction\": {\"type\": \"NONE\"}, \"ruleGroupType\": \"RuleGroup\"}],
        \"postProcessRuleGroups\": [], \"defaultAction\": {\"type\": \"ALLOW\"}}"}
    Type: AWS::FMS::Policy
```

Furthermore, attempting to add a troposphere Sub() object around the _ManagedServiceData_ string results in an error that the Sub() object is not JSON Serializable. 

I propose that an additional helper object be defined in FMS.py that allows further breakout of these items and moves the json_checker validation to the _ManagedServiceData_ definition under the new object.

I'm curious to know if anyone has this working as is.

Thanks!

**Comment by ev3rl0ng** [comment]
I patched it locally and was able to get it to work. After deployment, _Type_ may not be required per the resource status response in CloudFormation.

```
Stack operations on resource BaseProtectionsIntPolicy would fail starting from 03/01/2021 as the template has invalid properties. Please refer to the resource documentation to fix the template. Properties validation failed for resource BaseProtectionsIntPolicy with message: #/SecurityServicePolicyData: required key [Type] not found
```

I'll be in contact with our TAM and AWS Support to get clarification before creating a pull request for the patch.

Thanks!

**Comment by ev3rl0ng** [comment]
Not sure how to tie `json_checker` validation into the _ManagedServiceData_ property and still allow Sub() usage. Open for input on that.

**Comment by ev3rl0ng** [comment]
The attached pull request results in the format covered in the AWS Documentation:

```yaml
  BaseProtectionsIntPolicy:
    Properties:
      DeleteAllPolicyResources: true
      ExcludeResourceTags: false
      IncludeMap:
        ACCOUNT:
          - '123456789012'
        ORGUNIT: []
      PolicyName: Base-Protections-Int-Policy
      RemediationEnabled: false
      ResourceType: ResourceTypeList
      ResourceTypeList:
        - AWS::ElasticLoadBalancingV2::LoadBalancer
        - AWS::ApiGateway::Stage
      SecurityServicePolicyData:
        ManagedServiceData: !Sub '{"type": "WAFV2", "preProcessRuleGroups": [{"ruleGroupArn":
          null, "overrideAction": {"type": "COUNT"}, "managedRuleGroupIdentifier":
          {"version": null, "vendorName": "AWS", "managedRuleGroupName": "AWSManagedRulesCommonRuleSet"},
          "ruleGroupType": "ManagedRuleGroup"}, {"ruleGroupArn": null, "overrideAction":
          {"type": "COUNT"}, "managedRuleGroupIdentifier": {"version": null, "vendorName":
          "AWS", "managedRuleGroupName": "AWSManagedRulesAmazonIpReputationList"},
          "ruleGroupType": "ManagedRuleGroup"}, {"ruleGroupArn": "${BaseIntRuleGroup.Arn}",
          "overrideAction": {"type": "NONE"}, "ruleGroupType": "RuleGroup"}], "postProcessRuleGroups":
          [], "defaultAction": {"type": "ALLOW"}}'
        Type: WAFV2
    Type: AWS::FMS::Policy
```
When used as follows:

```python
from troposphere import fms, Sub

# ... redacted ...

policy_obj = fms.Policy(
    title="BaseProtectionsIntPolicy",
    PolicyName="Base-Protections-Int-Policy",
    DeleteAllPolicyResources=True,
    ExcludeResourceTags=False,
    RemediationEnabled=False,
    ResourceType="ResourceTypeList",
    ResourceTypeList=["AWS::ElasticLoadBalancingV2::LoadBalancer", "AWS::ApiGateway::Stage"],
    IncludeMap={
        "ACCOUNT": [ "123456789012" ],
        "ORGUNIT": []
    },
    SecurityServicePolicyData=fms.SecurityServicePolicyData(
        Type="WAFV2",
        ManagedServiceData=Sub(generated_managed_service_data)
    )
)
```
