### ISSUE TITLE
OutpostArn not supported in Subnet

### ISSUE THREAD

**Issue by aashishgaba-cn** [cloudtools/troposphere#1849]
There is no support for `OutpostArn` property in Subnet
[Troposphere documentation](https://troposphere.readthedocs.io/en/latest/_modules/troposphere/ec2.html#Subnet)
```
class Subnet(AWSObject):
    resource_type = "AWS::EC2::Subnet"

    props = {
        'AssignIpv6AddressOnCreation': (boolean, False),
        'AvailabilityZone': (basestring, False),
        'CidrBlock': (basestring, True),
        'Ipv6CidrBlock': (basestring, False),
        'MapPublicIpOnLaunch': (boolean, False),
        'Tags': ((Tags, list), False),
        'VpcId': (basestring, True),
    }
```

[Cloudformation Subnet template ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet.html)
```
Type: AWS::EC2::Subnet
Properties: 
  AssignIpv6AddressOnCreation: Boolean
  AvailabilityZone: String
  CidrBlock: String
  Ipv6CidrBlock: String
  MapPublicIpOnLaunch: Boolean
  OutpostArn: String
  Tags: 
    - Tag
  VpcId: String

```
