### ISSUE TITLE
ECR CRR ReplicationConfiguration.ReplicationConfiguration has incorrect name (ReplicationConfigurationProperty)

### ISSUE THREAD

**Issue by TsimpDim** [cloudtools/troposphere#1994]
As per the spec, this property is:

```
    "AWS::ECR::ReplicationConfiguration.ReplicationConfiguration": {
      "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecr-replicationconfiguration-replicationconfiguration.html",
      "Properties": {
        "Rules": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecr-replicationconfiguration-replicationconfiguration.html#cfn-ecr-replicationconfiguration-replicationconfiguration-rules",
          "UpdateType": "Mutable",
          "Required": true,
          "Type": "List",
          "ItemType": "ReplicationRule"
        }
      }
    }
```

however in the codebase it is called `ReplicationConfigurationProperty`

Relevant lines:
https://github.com/cloudtools/troposphere/blob/f286aed5a9e09d1b2337fceec51d169bf2faddfe/troposphere/ecr.py#L60-L65

I understand this could be fixed by adding a file for ecr under `script/patches`, is that correct?

For me this connects to #1993 as I found them when adding CRR to a project. Let me know how I can help :)

**Comment by markpeek** [comment]
Thank you for the issue. I fixed the other issue but left this one due to backward compatibility. I noted it in the patches so I can change it in a future major version.

**Comment by spacez320** [comment]
Also experienced this issue today, not sure how to work around it.

```python
        replication_configuration: ecr.ReplicationConfiguration = ecr.ReplicationConfiguration(
            "ReplicationConfiguration",
            ReplicationConfigurationProperty=ecr.ReplicationConfigurationProperty(
                Rules=[
                    ecr.ReplicationRule(
                        Destinations=[
                            ...
                        ],
                    )
                ]
            ),
        )
        template.add_resource(replication_configuration)
```

Generated CloudFormation:

```yaml
#
# NOTE: This file was automatically generated by Troposphere. Do not directly edit!

Resources:
  ReplicationConfiguration:
    Properties:
      ReplicationConfigurationProperty:
        Rules:
          - Destinations:
              ...
    Type: AWS::ECR::ReplicationConfiguration
```

In CloudFormation:

> Properties validation failed for resource SharedReplicationConfiguration with message: #: required key [ReplicationConfiguration] not found #: extraneous key [ReplicationConfigurationProperty] is not permitted
