### ISSUE TITLE
GroupId should not be required in AWS::EC2::SecurityGroup Egress

### ISSUE THREAD

**Issue by pawelrubin** [cloudtools/troposphere#2045]
## Problem

**troposphere** incorrectly identifies `GroupId` parameter of `SecurityGroupEgress` in `AWS::EC2::SecurityGroup` as required.

## Context
`GroupId` is a required parameter in [`AWS::EC2::SecurityGroupEgress`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-security-group-egress.html) type, however not in [AWS::EC2::SecurityGroup Egress](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-rule.html)

The template below is a valid Cloudformation template
```yaml
Parameters:
  DefaultSecurityGroup:
    Type: String
  VpcId:
    Type: String

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My security group
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          SourceSecurityGroupId:
            Ref: DefaultSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0
```

## Steps to reproduce

Consider the code below

```python
from troposphere import Parameter, Ref, Template
from troposphere.ec2 import SecurityGroup, SecurityGroupEgress, SecurityGroupIngress

template = Template()

vpc_id = template.add_parameter(Parameter("VpcId", Type="String"))
default_security_group = template.add_parameter(Parameter("DefaultSecurityGroup", Type="String"))

template.add_resource(
    SecurityGroup(
        "MySecurityGroup",
        GroupDescription="My security group",
        VpcId=Ref(vpc_id),
        SecurityGroupIngress=[
            SecurityGroupIngress(
                title=None,
                IpProtocol="tcp",
                FromPort=0,
                ToPort=65535,
                SourceSecurityGroupId=Ref(default_security_group),
            )
        ],
        SecurityGroupEgress=[
            SecurityGroupEgress(
                title=None,
                IpProtocol="-1",
                CidrIp="0.0.0.0/0",
            )
        ],
    )
)

print(template.to_yaml())
```

## Actual result
```shell
ValueError: Resource GroupId required in type AWS::EC2::SecurityGroupEgress
```
## Expected result

no errors
