### ISSUE TITLE
Possibly bugged template produced on a Ref to a AWS::KMS::Key

### ISSUE THREAD

**Issue by gautaz** [cloudtools/troposphere#2287]
Hello,

Currently a reference to a `AWS::KMS::Key` like this:

```python
dbKmsKey = template.add_resource(Key(
    "DbKmsKey",
)),

template.add_output(Output(
    "KeyOutput",
    Export=Export("KeyOutput"),
    Value=Ref(dbKmsKey),
))
```

produces this template:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Outputs:
  KeyOutput:
    Export:
      Name: KeyOutput
    Value: !Ref
      - Type: AWS::KMS::Key
Resources:
  DbKmsKey:
    Type: AWS::KMS::Key
```

which is wrong as CloudFormation is expecting a string as an output value.

Did I do something wrong?
Is this a bug?
